version: "3.11"

services:

  eshop:
    build:
      context: .
      dockerfile: docker/eshop/Dockerfile
    image: eshop:0.0.1-dev
    container_name: eshop
    command: bash docker/runserver.sh
    environment:
      - DB_HOST=eshop_db
      - DB_PORT=5432
    env_file:
      - config/.env/eshop.env
    depends_on:
      - eshop_db
    expose:
      - 8000
    networks:
      - nginx_network
      - eshop_db_network
#    volumes:
#      - ./eshop:/home/appuser/app


  warehouse:
    build:
      context: .
      dockerfile: docker/warehouse/Dockerfile
    image: warehouse:0.0.1-dev
    container_name: warehouse
    command: bash docker/runserver.sh
    environment:
      - DB_HOST=warehouse_db
      - DB_PORT=5432
    env_file:
      - config/.env/warehouse.env
    depends_on:
      - warehouse_db
    expose:
      - 8001
    networks:
      - warehouse_db_network
      - nginx_network
#    volumes:
#      - ./warehouse:/home/appuser/app


  eshop_db:
    container_name: eshop_db
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=eshop_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - eshop-db-data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - eshop_db_network


  warehouse_db:
    container_name: warehouse_db
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=warehouse_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - warehouse-db-data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - warehouse_db_network


  nginx:
    image: nginx
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    restart: on-failure
    networks:
      - nginx_network
    ports:
      - 80:80
    depends_on:
      - eshop
      - warehouse
    healthcheck:
      test: ["CMD-SHELL", "ps ax", "|", "grep nginx", "||", "exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  warehouse-db-data:
  eshop-db-data:


networks:
  eshop_db_network:
  nginx_network:
  warehouse_db_network: