# Generated by Django 4.2 on 2023-04-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookitem',
            old_name='palce',
            new_name='place',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In_Work', 'In Work'), ('Success', 'Success'), ('Fail', 'Fail')], max_length=7),
        ),
    ]
