# Generated by Django 4.2 on 2023-04-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookitem',
            name='code_of_book_item',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
