# Generated by Django 4.2 on 2023-04-17 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_bookitem_code_of_book_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookitem',
            name='code_of_book_item',
        ),
    ]
